### ISSUE TITLE
Issue with Auntie Poulet and Jezz Torrent's hands

### ISSUE THREAD

**Issue by CommandGenius** [gennariarmando/gtavc-xbox-hands#1]
![image](https://github.com/user-attachments/assets/f3e43c3e-cd10-48ab-9b2b-26f2ee44ecb0)

**Comment by gennariarmando** [comment]
You need xbox ped models to fix this, it's not the plugin.
[xbox_peds.zip](https://github.com/user-attachments/files/17266356/xbox_peds.zip)

**Comment by CommandGenius** [comment]
> You need xbox ped models to fix this, it's not the plugin. [xbox_peds.zip](https://github.com/user-attachments/files/17266356/xbox_peds.zip)

Thank you.
